//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordcards_Stack_Gadget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordcards_Stack_Gadget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе....
        /// </summary>
        public static string MenuItemTextAbout {
            get {
                return ResourceManager.GetString("MenuItemTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string MenuItemTextChangeCard {
            get {
                return ResourceManager.GetString("MenuItemTextChangeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string MenuItemTextClose {
            get {
                return ResourceManager.GetString("MenuItemTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая карточка.
        /// </summary>
        public static string MenuItemTextCurrentCard {
            get {
                return ResourceManager.GetString("MenuItemTextCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string MenuItemTextDeleteCard {
            get {
                return ResourceManager.GetString("MenuItemTextDeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую карточку.
        /// </summary>
        public static string MenuItemTextNewCard {
            get {
                return ResourceManager.GetString("MenuItemTextNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая карточка.
        /// </summary>
        public static string MenuItemTextNextCard {
            get {
                return ResourceManager.GetString("MenuItemTextNextCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть карточки из файла....
        /// </summary>
        public static string MenuItemTextOpenFile {
            get {
                return ResourceManager.GetString("MenuItemTextOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в Play mode.
        /// </summary>
        public static string MenuItemTextPlayMode {
            get {
                return ResourceManager.GetString("MenuItemTextPlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущая карточка.
        /// </summary>
        public static string MenuItemTextPreviousCard {
            get {
                return ResourceManager.GetString("MenuItemTextPreviousCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить карточки в файл....
        /// </summary>
        public static string MenuItemTextSaveTofile {
            get {
                return ResourceManager.GetString("MenuItemTextSaveTofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать Рейтинг.
        /// </summary>
        public static string MenuItemTextSetRank {
            get {
                return ResourceManager.GetString("MenuItemTextSetRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить изменения.
        /// </summary>
        public static string ToolTipDiscardChanges {
            get {
                return ResourceManager.GetString("ToolTipDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример использования.
        /// </summary>
        public static string ToolTipExample {
            get {
                return ResourceManager.GetString("ToolTipExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод примера.
        /// </summary>
        public static string ToolTipExampleTranslate {
            get {
                return ResourceManager.GetString("ToolTipExampleTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевернуть.
        /// </summary>
        public static string ToolTipFlip {
            get {
                return ResourceManager.GetString("ToolTipFlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string ToolTipSaveChanges {
            get {
                return ResourceManager.GetString("ToolTipSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транскрипция.
        /// </summary>
        public static string ToolTipTranscription {
            get {
                return ResourceManager.GetString("ToolTipTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский перевод.
        /// </summary>
        public static string ToolTipWord {
            get {
                return ResourceManager.GetString("ToolTipWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский перевод.
        /// </summary>
        public static string ToolTipWordTranslate {
            get {
                return ResourceManager.GetString("ToolTipWordTranslate", resourceCulture);
            }
        }
    }
}
